arm/coproc: Remove unused variable from dummy remote processor
Fix compile time error:
coproc_xxx.c:30:17: error: 'coproc_wait_time' defined but not used
[-Werror=unused-variable]
static s_time_t coproc_wait_time = MILLISECS(500);

Signed-off-by: Anastasiia Lukianenko <anastasiia_lukianenko@epam.com>
Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>